modLoader="javafml"
loaderVersion="[47,)"

license="MIT"

[[mods]]
modId="virtual_redstone_wire"
version="${version}"
displayName="Virtual Redstone Wire"
logoFile="virtual_redstone_wire.png"
credits="JudeBlack"
authors="JudeBlack"
description='''
A Minecraft mod for long-distance redstone signal transmission that does not rely on physical redstone blocks, supporting one-to-one, one-to-many, and many-to-one connections.
'''

[[dependencies.virtual_redstone_wire]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.virtual_redstone_wire]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
